### ISSUE TITLE
build文件夹里面bochsrc文件内有两个乱码

### ISSUE THREAD

**Issue by swaggypg** [diadestiny/GeekOS_course_desgin#1]
师兄好，我试了一下把bochsrc里的乱码改成引号 " ，运行bochs的时候出现黑色框，但是提示ata0-0和ata0-1有问题，所以乱码原本是什么东西呢？
![image](https://user-images.githubusercontent.com/35105404/170162337-f09e6a8d-974c-4b7c-803c-382069d2a6c4.png)

**Comment by swaggypg** [comment]
就是这边的两个乱码
![image](https://user-images.githubusercontent.com/35105404/170162427-1ccead6e-abfe-48eb-a3dd-ff657b337acf.png)

**Comment by diadestiny** [comment]
> 师兄好，我试了一下把bochsrc里的乱码改成引号 " ，运行bochs的时候出现黑色框，但是提示ata0-0和ata0-1有问题，所以乱码原本是什么东西呢？ ![image](https://user-images.githubusercontent.com/35105404/170162337-f09e6a8d-974c-4b7c-803c-382069d2a6c4.png)

这个乱码在我的系统编译和运行是没有影响的，感觉影响不大，我当时是照着http://www.cs.uni-salzburg.at/~ckrainer/OS-Winter-2006/BOS/bos-1.0-src.tar.gz 这个bos系统改的，不好意思 我忘记这个乱码原来是啥了，建议先不需要修改。

我这个代码之前还没试过在ubuntu9成功跑通，你这个报错问题应该还是系统不兼容问题，我建议你开一个ubuntu16虚拟机(镜像链接我已经给出了)，按照我readme的步骤来配好，先安装bochs这些，最主要是gcc-5.4.0、nasm-2.08.2这两个版本要对，gcc-5.4.0已经自带了 不需要安装了，所以安装nasm得检查版本是不是2.08.2，如果不是，需要去官网下载对应版本安装，不然可能还是会报别的错。

有问题欢迎联系，readme和博客基本写的很详细了

**Comment by diadestiny** [comment]
我用新开的ubuntu16.04是可以跑通这份代码的，如果配置上还有问题和坑欢迎提问。
(由于时间问题，还没尝试过ubuntu9，大概率系统不兼容）

**Comment by swaggypg** [comment]
> 我用新开的ubuntu16.04是可以跑通这份代码的，如果配置上还有问题和坑欢迎提问。 (由于时间问题，还没尝试过ubuntu9，大概率系统不兼容）

好嘞好嘞谢谢师兄
